feeds:
  - name: "Decoding ML"
    author: "Paul Iusztin"
    url: "https://decodingml.substack.com/feed"
  - name: "The Neural Maze"
    author: "Miguel Otero"
    url: "https://theneuralmaze.substack.com/feed"
  - name: "The Machine Learning Engineer"
    author: "Alejandro Saucedo"
    url: "https://machinelearning.substack.com/feed"
  - name: "Data Science Weekly"
    author: "Hannah & Sebastian"
    url: "https://datascienceweekly.substack.com/feed"
  - name: "Machine Learning Pills"
    author: "David Andrés"
    url: "https://mlpills.substack.com/feed"
  - name: "Ahead of AI"
    author: "Sebastian Raschka"
    url: "https://magazine.sebastianraschka.com/feed"
  - name: "One Useful Thing"
    author: "Ethan Mollick"
    url: "https://oneusefulthing.substack.com/feed"
  - name: "Last Week in AI"
    author: "Davis Blalock"
    url: "https://lastweekin.ai/feed"
  - name: "Import AI"
    author: "Jack Clark"
    url: "https://importai.substack.com/feed"
  - name: "Applied ML"
    author: "Gaurav Chakravorty"
    url: "https://appliedml.substack.com/feed"
  - name: "MLOps Newsletter"
    author: "Bugra Akyildiz"
    url: "https://mlops.substack.com/feed"